[web]
development = true
address = "127.0.0.1"
port = 443
ports = [17091]
loginUrl = "login.growserver.app:8080"
cdnUrl = "growserver-cache.netlify.app"

[web.maintenance]
enable = false
message = "Maintenance Woi"

[web.tls]
key = "./assets/ssl/server.key"
cert = "./assets/ssl/server.crt"

[webFrontend]
root = "./.cache/website"
port = 8080

[webFrontend.tls]
key = "./.cache/ssl/_wildcard.growserver.app-key.pem"
cert = "./.cache/ssl/_wildcard.growserver.app.pem"

[server]
bypassVersionCheck = true
logLevel = "info"